---
# IncompatibleAPIPluginLoader configuration file.

# Whether to load all incompatible APIs except the ones below, or load no incompatible APIs except the ones below.
# All: To load plugins with any incompatible API except the ones below.
# None: To load no plugins with incompatible API except the ones below.
Load-API: All

# The API versions to except from the setting above.
# If the above is set to 'All': Loads plugins with any incompatible API except the ones below.
# If it is set to 'None': Loads no plugins with an incompatible API except the ones below.
Except-APIs:
- 1.0.0

